// Cover pictures for the demo books (Open Library, English editions, found by title and author).
// Used by the seed and by the migration that fills existing databases.
export const BOOK_IMAGES: Record<string, string> = {
  "1984": 'https://covers.openlibrary.org/b/id/15257423-L.jpg',
  "The Great Gatsby": 'https://covers.openlibrary.org/b/id/14369845-L.jpg',
  "To Kill a Mockingbird": 'https://covers.openlibrary.org/b/id/15153500-L.jpg',
  "Pride and Prejudice": 'https://covers.openlibrary.org/b/id/15043406-L.jpg',
  "The Catcher in the Rye": 'https://covers.openlibrary.org/b/id/15172466-L.jpg',
  "Brave New World": 'https://covers.openlibrary.org/b/id/15170948-L.jpg',
  "Moby-Dick": 'https://covers.openlibrary.org/b/id/11978426-L.jpg',
  "The Hobbit": 'https://covers.openlibrary.org/b/id/14624642-L.jpg',
  "Fahrenheit 451": 'https://covers.openlibrary.org/b/id/15171080-L.jpg',
  "Jane Eyre": 'https://covers.openlibrary.org/b/id/15164202-L.jpg',
  "Dune": 'https://covers.openlibrary.org/b/id/14020316-L.jpg',
  "Neuromancer": 'https://covers.openlibrary.org/b/id/14389185-L.jpg',
  "The Left Hand of Darkness": 'https://covers.openlibrary.org/b/id/14920821-L.jpg',
  "The Martian Chronicles": 'https://covers.openlibrary.org/b/id/14828149-L.jpg',
  "A Wizard of Earthsea": 'https://covers.openlibrary.org/b/id/15231478-L.jpg',
  "The Fellowship of the Ring": 'https://covers.openlibrary.org/b/id/15244480-L.jpg',
  "The Name of the Wind": 'https://covers.openlibrary.org/b/id/13409756-L.jpg',
  "Good Omens": 'https://covers.openlibrary.org/b/id/14657945-L.jpg',
  "And Then There Were None": 'https://covers.openlibrary.org/b/id/15159278-L.jpg',
  "The Hound of the Baskervilles": 'https://covers.openlibrary.org/b/id/4638176-L.jpg',
  "Gone Girl": 'https://covers.openlibrary.org/b/id/12498395-L.jpg',
  "The Big Sleep": 'https://covers.openlibrary.org/b/id/11518032-L.jpg',
  "Sapiens": 'https://covers.openlibrary.org/b/id/11481587-L.jpg',
  "The Pragmatic Programmer": 'https://covers.openlibrary.org/b/id/15111148-L.jpg',
  "Thinking, Fast and Slow": 'https://covers.openlibrary.org/b/id/13290715-L.jpg',
  "A Brief History of Time": 'https://covers.openlibrary.org/b/id/14829099-L.jpg',
  "The Guns of August": 'https://covers.openlibrary.org/b/id/8261438-L.jpg',
  "SPQR": 'https://covers.openlibrary.org/b/id/10382021-L.jpg',
  "The Silk Roads": 'https://covers.openlibrary.org/b/id/15233611-L.jpg',
  "Persuasion": 'https://covers.openlibrary.org/b/id/14617883-L.jpg',
  "Outlander": 'https://covers.openlibrary.org/b/id/10745175-L.jpg',
  "Me Before You": 'https://covers.openlibrary.org/b/id/15222783-L.jpg',
  "Leaves of Grass": 'https://covers.openlibrary.org/b/id/14981306-L.jpg',
  "Ariel": 'https://covers.openlibrary.org/b/id/6974152-L.jpg',
  "Milk and Honey": 'https://covers.openlibrary.org/b/id/15162565-L.jpg',
  "The Waste Land": 'https://covers.openlibrary.org/b/id/15184471-L.jpg',
}
